name: php
display: php good
category: web
description: >
  A really simple and definately unhackable website.
  So much so that the monkey developer wants to show everyone they are using php at /info.php
  "flag.txt" is in the same directory as the web page.
hints: >
- {"text" : "What is the PHP version, and is it safe?", "cost" : 5}
flags:
- "kucss{monk3y_c0uNt}"
points:
- 20
